#!/usr/bin/env python3
"""Render project specialists from the shared router contract and role sources."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESCRIPTIONS = {
    "evidence-investigator": "Resolve a bounded independent evidence question using sources and checks; return findings and limits to the coordinator.",
    "evidence-reviewer": "Independently verify support and completeness before material operational conclusions are delivered; return acceptance or specific defects.",
}


def projections() -> dict[Path, str]:
    router = (ROOT / "kernel/AGENTS.md").read_text(encoding="utf-8")
    contract = router.split("## Evidence contract\n", 1)[1].split("\n## ", 1)[0].strip()
    output = {}
    for name, description in DESCRIPTIONS.items():
        role = (ROOT / "kernel/90-Meta/specialists" / f"{name}.md").read_text(encoding="utf-8").strip()
        prompt = "# Shared evidence contract\n\n" + contract + "\n\n" + role + "\n"
        warning = "Generated by scripts/render_specialists.py; edit kernel/AGENTS.md or kernel/90-Meta/specialists instead."
        codex = f"# {warning}\nname = {json.dumps(name)}\ndescription = {json.dumps(description)}\nsandbox_mode = \"read-only\"\ndeveloper_instructions = {json.dumps(prompt)}\n"
        output[ROOT / f"kernel/.codex/agents/{name}.toml"] = codex
        for harness, fields in (
            ("claude", "disallowedTools: Agent, Write, Edit, NotebookEdit\n"),
            ("cursor", "readonly: true\n"),
        ):
            content = f"---\nname: {name}\ndescription: {json.dumps(description)}\n{fields}---\n\n<!-- {warning} -->\n\n{prompt}"
            output[ROOT / f"kernel/.{harness}/agents/{name}.md"] = content
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, text in projections().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        print("Stale specialist projections: " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
